name: A workflow for my Hello World file
on: push
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Echo hello world
      run: echo Hello World
    - name: Check out index code
      run: cat index.html
